import { RiMacbookLine, RiTerminalBoxLine } from "@remixicon/react";
import { GridItem } from "@/types";
import {
  GitHubLogoIcon,
  InstagramLogoIcon,
  LinkedInLogoIcon,
} from "@radix-ui/react-icons";

export const gridItems: GridItem[] = [
  {
    layout: "2x2",
    type: "SOCIAL",
    title: "Github",
    username: "@ahmedmayara",
    description:
      "My name is Ahmed Mayara and I’m a software developer. My main focus is high-quality, scalable software solutions that meet and exceed client expectations.",
    icon: GitHubLogoIcon,
    buttonText: "Follow",
    buttonVariant: "gray",
    buttonLink: "https://github.com/ahmedmayara",
    url: "https://github.com/ahmedmayara",
  },
  {
    layout: "1x2",
    type: "SOCIAL",
    title: "Linkedin",
    icon: LinkedInLogoIcon,
    username: "@ahmedmayara",
    buttonText: "Connect",
    buttonVariant: "blue",
    buttonLink: "https://www.linkedin.com/in/ahmed-mayara-1393882a0/",
    url: "https://www.linkedin.com/in/ahmed-mayara-1393882a0/",
  },
  {
    layout: "1x2",
    type: "SOCIAL",
    title: "Instagram",
    username: "@ahmedmayara",
    icon: InstagramLogoIcon,
    buttonText: "Follow",
    buttonVariant: "pink",
    buttonLink: "https://www.instagram.com/ahmeedmayara/",
    url: "https://www.instagram.com/ahmeedmayara/",
  },
  {
    layout: "2x4",
    type: "PROJECT",
    title: "Residia",
    description:
      "Residia is a powerful and intuitive application designed to help you discover the perfect home for your needs.",
    techStack: [
      "React",
      "Next.js",
      "Tailwind CSS",
      "TypeScript",
      "MongoDB",
      "Prisma",
    ],
    buttonText: "View on Github",
    buttonVariant: "gray",
    image: "/images/residia-cover.png",
    buttonLink: "https://github.com/ahmedmayara/residia-app",
    demoLink: "https://residia.vercel.app/",
  },
  {
    layout: "2x2",
    type: "EXPERIENCE",
    title: "Software Engineer",
    icon: RiTerminalBoxLine,
    description: "Devoxys",
    location: "Mégrine, Ben Arous, Tunisia",
    startDate: "September 2025",
    endDate: "Present",
  },
  {
    layout: "2x2",
    type: "EXPERIENCE",
    title: "Software Developer Intern",
    icon: RiMacbookLine,
    description: "Neopolis Development",
    location: "Nabeul, Tunisia",
    startDate: "January 2021",
    endDate: "March 2021",
  },
  {
    layout: "2x4",
    type: "PROJECT",
    title: "Oladoc",
    description:
      "Oladoc is a platform that connects patients with doctors and helps them book appointments online.",
    techStack: [
      "React",
      "Next.js",
      "Tailwind CSS",
      "TypeScript",
      "MongoDB",
      "Prisma",
      "Pusher",
    ],
    buttonText: "View on Github",
    buttonVariant: "gray",
    image: "/images/oladoc-cover.png",
    buttonLink: "https://github.com/ahmedmayara/oladoc",
    demoLink: "https://oladoc.online/",
  },
  {
    layout: "2x4",
    type: "PROJECT",
    title: "Shadcn Vue",
    description:
      "An unofficial, community-led Vue port of shadcn/ui. This project was born out of the need for a similar project for the Vue ecosystem.",
    techStack: ["Vue", "Tailwind CSS", "TypeScript", "Vite", "VitePress"],
    buttonText: "View on Github",
    buttonVariant: "gray",
    image: "/images/shadcn-vue-cover.png",
    buttonLink: "https://github.com/radix-vue/shadcn-vue",
    demoLink: "https://www.shadcn-vue.com/",
  },
] as const;

export const config = {
  name: "Ahmed Mayara",
  title: "Software Engineer",
  description: "Building scalable software solutions for the web.",
  bio: "My name is Ahmed Mayara and I’m a software engineer. My main focus is building high-quality, scalable software solutions that meet and exceed client expectations.",
  location: "Nabeul, Tunisia",
  locationUrl: "https://www.google.com/maps/place/Nabeul/",
  email: "ahmedmayara789@gmail.com",
  items: gridItems,
} as const;
